steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/code-test-back-pipeline-service:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/code-test-back-pipeline-service"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
          "run",
          "deploy",
          "code-test-back-pipeline-service",
          "--image",
          "gcr.io/$PROJECT_ID/code-test-back-pipeline-service:${SHORT_SHA}",
          "--port",
          "8000",
          "--region",
          "europe-west1",
          "--platform",
          "managed",
          "--allow-unauthenticated",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
      args:
        [
            "run",
            "services",
            "update",
            "code-test-back-pipeline-service",
            "--add-cloudsql-instances",
            "codetestbdd:europe-west1:codetest-bdd-1",
            "--set-env-vars",
            "CLOUD_SQL_CONNECTION_NAME=codetestbdd:europe-west1:codetest-bdd-1,DB_USER=postgres,DB_PASS=CodeWorks,DB_NAME=postgres"
        ]
